name: Testing Game  CI/CD.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-and-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Startup Typing Game
        run: yarn build

      - name: Run Tests
        run: yarn test
      

